### ISSUE TITLE
namespace-emitter

### ISSUE THREAD

**Issue by arturi** [yoshuawuyts/nanobus#1]
Cool lib! I’ve been using `[namespace-emitter](https://www.npmjs.com/package/namespace-emitter)`, not sure if you’ve seen it, seems smaller:

```
$ mingz nanobus
    4967

$ mingz namespace-emitter
     725
```

Just FYI, maybe there are some ideas to share.

**Comment by yoshuawuyts** [comment]
Heya, thanks for pointing me to that package. I quite like it tbh. I think the main difference in size is because we support a * listener and keep most of the API similar to how now node does things. I actually considered using node's emitter, but this package trimmed down the size by 3x so I figured it was worth it. Hope this kind of explains the reasoning behind this package; thanks again!

**Comment by arturi** [comment]
> we support a * listener

it does too, and also namespaces, so if you listen to all `example` namespace events, it will fire on`example:my-event` too:

```js
emitter.on('*', function () {
  console.log('all events emitted', this.event)
})
 
emitter.on('example', function () {
  console.log('example event emitted')
})
 
emitter.emit('example')
```

Demo: http://www.webpackbin.com/NJ1z_k4cM

> API similar to how now node does things

:ok_hand:
